config/routes.rb
Rails.application.routes.draw do
  get 'products/index'
  get 'products/new'

  resources :products

  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end

  def new
  	@product = Product.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apka2</title>
  
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>FAB STUFF</h1>
<p>Brilliant clothing ideas!</p>

<%= link_to 'Add new product', new_product_path %>

<table class="table">
	<thead>
		<th>Photo</th>
		<th>Name</th>
		<th>Description</th>
		<th>Category</th>
		<th>Price</th>
	</thead>
	<tbody>
	<% @products.each do |product| %> 
		<tr>
			<td><%= image_tag(product.image, class:"picture") %></td>
			<td><%= product.name %></td>
			<td><%= product.description %></td>
			<td><%= product.category %></td>
			<td><%= product.price %> $</td>
		</tr>
	<%end%>


	</tbody>
</table>

app/views/products/new.html.erb
<h1>Add new product:</h1>

<%= render "form" %>

<%= link_to 'Back to products', products_path %>